// Generated by scripts/gtfs-build.mts. Do not edit.
import type { PairFile } from "../schema";

export const pairs: Record<string, () => Promise<PairFile>> = {
  "bangkok__chiang-mai": () => import("./bangkok__chiang-mai.json").then((m) => m.default as unknown as PairFile),
  "bangkok__hat-yai": () => import("./bangkok__hat-yai.json").then((m) => m.default as unknown as PairFile),
  "bangkok__krabi": () => import("./bangkok__krabi.json").then((m) => m.default as unknown as PairFile),
  "bangkok__pattaya": () => import("./bangkok__pattaya.json").then((m) => m.default as unknown as PairFile),
  "bangkok__phuket": () => import("./bangkok__phuket.json").then((m) => m.default as unknown as PairFile),
  "bangkok__surat-thani": () => import("./bangkok__surat-thani.json").then((m) => m.default as unknown as PairFile),
  "chiang-mai__bangkok": () => import("./chiang-mai__bangkok.json").then((m) => m.default as unknown as PairFile),
  "hat-yai__bangkok": () => import("./hat-yai__bangkok.json").then((m) => m.default as unknown as PairFile),
  "hat-yai__krabi": () => import("./hat-yai__krabi.json").then((m) => m.default as unknown as PairFile),
  "krabi__bangkok": () => import("./krabi__bangkok.json").then((m) => m.default as unknown as PairFile),
  "krabi__hat-yai": () => import("./krabi__hat-yai.json").then((m) => m.default as unknown as PairFile),
  "krabi__phuket": () => import("./krabi__phuket.json").then((m) => m.default as unknown as PairFile),
  "krabi__surat-thani": () => import("./krabi__surat-thani.json").then((m) => m.default as unknown as PairFile),
  "pattaya__bangkok": () => import("./pattaya__bangkok.json").then((m) => m.default as unknown as PairFile),
  "phuket__bangkok": () => import("./phuket__bangkok.json").then((m) => m.default as unknown as PairFile),
  "phuket__krabi": () => import("./phuket__krabi.json").then((m) => m.default as unknown as PairFile),
  "surat-thani__bangkok": () => import("./surat-thani__bangkok.json").then((m) => m.default as unknown as PairFile),
  "surat-thani__krabi": () => import("./surat-thani__krabi.json").then((m) => m.default as unknown as PairFile),
};
