// Generated from flag-icons' SVGs by scripts/flags.mts. Do not edit by hand: run `pnpm flags`, or draw a flag
// in flag-art.ts to override it. A space is a cell outside the flag.
import type { FlagArt } from "./flag-art";

export const GENERATED_FLAGS: Record<string, FlagArt> = {
  AD: {
    inks: { A: "#0018a8", B: "#fedf00", C: "#d0103a", D: "#c7b37f" },
    rows: [
      "AAAABBBBBBCCCC",
      "AAAABBBBBBCCCC",
      "AAAABBBBBBCCCC",
      "AAAABDDDDBCCCC",
      "AAAABDDBDBCCCC",
      "AAAABDBBDBCCCC",
      "AAAABDDDDBCCCC",
      "AAAABBBBBBCCCC",
      "AAAABBBBBBCCCC",
      "AAAABBBBBBCCCC",
    ],
  },
  AE: {
    inks: { A: "#ff0000", B: "#00732f", C: "#ffffff", D: "#000001" },
    rows: [
      "AAAAABBBBBBBBB",
      "AAAAABBBBBBBBB",
      "AAAAABBBBBBBBB",
      "AAAAACCCCCCCCC",
      "AAAAACCCCCCCCC",
      "AAAAACCCCCCCCC",
      "AAAAACCCCCCCCC",
      "AAAAADDDDDDDDD",
      "AAAAADDDDDDDDD",
      "AAAAADDDDDDDDD",
    ],
  },
  AF: {
    inks: { A: "#000001", B: "#bf0000", C: "#009900", D: "#ffffff" },
    rows: [
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAADDDDCCCCC",
      "AAAAADDDDCCCCC",
      "AAAAABDDBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
    ],
  },
  AG: {
    inks: { A: "#000001", B: "#ce1126", C: "#fcd116", D: "#0072c6", E: "#ffffff" },
    rows: [
      "AAAAAAAAAAAAAA",
      "BAAAAACCAAAAAB",
      "BBAAACCCCAAABB",
      "BBAACCCCCCAABB",
      "BBBDDDDDDDDBBB",
      "BBBBDDDDDDBBBB",
      "BBBBEEEEEEBBBB",
      "BBBBBEEEEBBBBB",
      "BBBBBBEEBBBBBB",
      "BBBBBBBBBBBBBB",
    ],
  },
  AL: {
    inks: { A: "#ff0000", B: "#000001" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAABBBBBBAAAA",
      "AAAABBBBBBAAAA",
      "AAAABBBBBBAAAA",
      "AAAAABBBBAAAAA",
      "AAAAAABBAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
    ],
  },
  AM: {
    inks: { A: "#d90012", B: "#0033a0", C: "#f2a800" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
    ],
  },
  AO: {
    inks: { A: "#ff0000", B: "#ffec00", C: "#000001" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAABBAAAAAAA",
      "AAAAAAAAAAAAAA",
      "CCCCBCCCCCCCCC",
      "CCCCCBBCCCCCCC",
      "CCCCBBCBCCCCCC",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
    ],
  },
  AR: {
    inks: { A: "#74acdf", B: "#ffffff", C: "#f6b40e" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "BBBBBBBBBBBBBB",
      "BBBBBBCCBBBBBB",
      "BBBBBBCCBBBBBB",
      "BBBBBBBBBBBBBB",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
    ],
  },
  AT: {
    inks: { A: "#c8102e", B: "#ffffff" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
    ],
  },
  AU: {
    inks: { A: "#ffffff", B: "#ff0000", C: "#00008b" },
    rows: [
      "AAABABACCCCCCC",
      "AAABAAACCCCCCC",
      "BBBBBBBCCCCCCC",
      "AAABAAACCCCCAC",
      "ABABAAACACCCCC",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
      "CCAAACCCCCCCCC",
      "CCCACCCCCCCCCC",
      "CCCCCCCCCCCCCC",
    ],
  },
  AZ: {
    inks: { A: "#00b9e4", B: "#ed2939", C: "#ffffff", D: "#3f9c35" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "BBBBBBCBBBBBBB",
      "BBBBBCBBCBBBBB",
      "BBBBBCBBCBBBBB",
      "BBBBBBCBBBBBBB",
      "DDDDDDDDDDDDDD",
      "DDDDDDDDDDDDDD",
      "DDDDDDDDDDDDDD",
    ],
  },
  BA: {
    inks: { A: "#000099", B: "#ffcc00", C: "#ffffff" },
    rows: [
      "AAABBBBBBBBBBA",
      "AACABBBBBBBBBA",
      "AAACABBBBBBBBA",
      "AAAACCABBBBBBA",
      "AAAAAACABBBBBA",
      "AAAAAAAAABBBBA",
      "AAAAAAACAABBBA",
      "AAAAAAAACCABBA",
      "AAAAAAAAAACABA",
      "AAAAAAAAAAACAA",
    ],
  },
  BB: {
    inks: { A: "#00267f", B: "#ffc726", C: "#000001" },
    rows: [
      "AAAAABBBBAAAAA",
      "AAAAABBBBAAAAA",
      "AAAAABBBBAAAAA",
      "AAAAABBBBAAAAA",
      "AAAAACBBCAAAAA",
      "AAAAABCCBAAAAA",
      "AAAAABBBBAAAAA",
      "AAAAABBBBAAAAA",
      "AAAAABBBBAAAAA",
      "AAAAABBBBAAAAA",
    ],
  },
  BD: {
    inks: { A: "#006a4e", B: "#f42a41" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAABBBBAAAAAA",
      "AAABBBBBBAAAAA",
      "AAABBBBBBBAAAA",
      "AAABBBBBBBAAAA",
      "AAABBBBBBAAAAA",
      "AAAABBBBAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
    ],
  },
  BE: {
    inks: { A: "#000001", B: "#ffd90c", C: "#f31830" },
    rows: [
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
    ],
  },
  BF: {
    inks: { A: "#de0000", B: "#fff300", C: "#35a100" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAABBAAAAAA",
      "AAAABBBBBBAAAA",
      "CCCCCBBBBCCCCC",
      "CCCCCBBBBCCCCC",
      "CCCCCBCCBCCCCC",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
    ],
  },
  BG: {
    inks: { A: "#ffffff", B: "#00966e", C: "#d62612" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
    ],
  },
  BH: {
    inks: { A: "#ffffff", B: "#ce1126" },
    rows: [
      "AAAABBBBBBBBBB",
      "AAAABBBBBBBBBB",
      "AAAABBBBBBBBBB",
      "AAAABBBBBBBBBB",
      "AAAABBBBBBBBBB",
      "AAAABBBBBBBBBB",
      "AAAABBBBBBBBBB",
      "AAAABBBBBBBBBB",
      "AAAABBBBBBBBBB",
      "AAAABBBBBBBBBB",
    ],
  },
  BI: {
    inks: { A: "#ffffff", B: "#cf0921", C: "#18b637" },
    rows: [
      "ABBBBBBBBBBBBA",
      "AABBBBBBBBBBAA",
      "CAAABBAABBAAAC",
      "CCCAAAAAAAACCC",
      "CCCCAAAAAACCCC",
      "CCCCABAABACCCC",
      "CCCAAAAAAAACCC",
      "CAAABBAABBAAAC",
      "AABBBBBBBBBBAA",
      "ABBBBBBBBBBBBA",
    ],
  },
  BJ: {
    inks: { A: "#319400", B: "#ffd600", C: "#de2110" },
    rows: [
      "AAAAAABBBBBBBB",
      "AAAAAABBBBBBBB",
      "AAAAAABBBBBBBB",
      "AAAAAABBBBBBBB",
      "AAAAAABBBBBBBB",
      "AAAAAACCCCCCCC",
      "AAAAAACCCCCCCC",
      "AAAAAACCCCCCCC",
      "AAAAAACCCCCCCC",
      "AAAAAACCCCCCCC",
    ],
  },
  BN: {
    inks: { A: "#f7e017", B: "#ffffff", C: "#000001", D: "#cf1126" },
    rows: [
      "AAAAAAAAAAAAAA",
      "BBBAAAAAAAAAAA",
      "BBBBBBAAAAAAAA",
      "CCBBBBDDBBAAAA",
      "CCCCCBBBBBBBBA",
      "ACCCDCCCDDBBBB",
      "AAAADDDDDCCCBB",
      "AAAAADDDDCCCCC",
      "AAAAAAAAAAACCC",
      "AAAAAAAAAAAAAA",
    ],
  },
  BO: {
    inks: { A: "#d52b1e", B: "#ffe000", C: "#007934" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "BBBBBBBBBBBBBB",
      "BBBBBBCBBBBBBB",
      "BBBBBBCCBBBBBB",
      "BBBBBBBBBBBBBB",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
    ],
  },
  BR: {
    inks: { A: "#229e45", B: "#f8e509", C: "#2b49a3", D: "#ffffff" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAABBAAAAAA",
      "AAAABBCCBBAAAA",
      "AAABBCCCCBBAAA",
      "ABBBCCCDCCBBBA",
      "ABBBCCCCCDBBBA",
      "AAABBCCCCBBAAA",
      "AAAABBCCBBAAAA",
      "AAAAAABBAAAAAA",
      "AAAAAAAAAAAAAA",
    ],
  },
  BS: {
    inks: { A: "#000001", B: "#08ced6", C: "#ffe900" },
    rows: [
      "ABBBBBBBBBBBBB",
      "AAABBBBBBBBBBB",
      "AAAABBBBBBBBBB",
      "AAAAAACCCCCCCC",
      "AAAAAAAACCCCCC",
      "AAAAAAAACCCCCC",
      "AAAAAACCCCCCCC",
      "AAAABBBBBBBBBB",
      "AAABBBBBBBBBBB",
      "ABBBBBBBBBBBBB",
    ],
  },
  BT: {
    inks: { A: "#ffd520", B: "#ff4e12", C: "#ffffff" },
    rows: [
      "AAAAAAAAAAAAAB",
      "AAAAAAAAAAAABB",
      "AAAAAAACCCCCBB",
      "AAAAAAACCCCCBB",
      "AAAAACCCCCCCBB",
      "AAAAACCCCBBBBB",
      "AAAACCCBCCCBBB",
      "AAACBCBBBBBBBB",
      "AABBBCBBBBBBBB",
      "ABBBBBBBBBBBBB",
    ],
  },
  BW: {
    inks: { A: "#00cbff", B: "#ffffff", C: "#000001" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "BBBBBBBBBBBBBB",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
      "BBBBBBBBBBBBBB",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
    ],
  },
  BY: {
    inks: { A: "#ce1720", B: "#ffffff", C: "#007c30" },
    rows: [
      "ABAAAAAAAAAAAA",
      "BBAAAAAAAAAAAA",
      "ABAAAAAAAAAAAA",
      "BAAAAAAAAAAAAA",
      "BBAAAAAAAAAAAA",
      "BBAAAAAAAAAAAA",
      "BAAAAAAAAAAAAA",
      "ABCCCCCCCCCCCC",
      "BBCCCCCCCCCCCC",
      "ABCCCCCCCCCCCC",
    ],
  },
  BZ: {
    inks: { A: "#ce1126", B: "#003f87", C: "#ffffff", D: "#007f00", E: "#ffd83c", F: "#552300" },
    rows: [
      "AAAAAAAAAAAAAA",
      "BBBBBCCCCBBBBB",
      "BBBBCCDDCCBBBB",
      "BBBCCEDDFCCBBB",
      "BBBCCECEFCCBBB",
      "BBBCCCCECCCBBB",
      "BBBCCCDDCCCBBB",
      "BBBBCCCCCCBBBB",
      "BBBBBCCCCBBBBB",
      "AAAAAAAAAAAAAA",
    ],
  },
  CA: {
    inks: { A: "#d52b1e", B: "#ffffff" },
    rows: [
      "AAABBBBBBBBAAA",
      "AAABBBBBBBBAAA",
      "AAABBBBBBBBAAA",
      "AAABBBAABBBAAA",
      "AAABAAAAABBAAA",
      "AAABBAAAABBAAA",
      "AAABBBABBBBAAA",
      "AAABBBBBBBBAAA",
      "AAABBBBBBBBAAA",
      "AAABBBBBBBBAAA",
    ],
  },
  CD: {
    inks: { A: "#007fff", B: "#f7d618", C: "#ce1021" },
    rows: [
      "AAAAAAAAAAAABC",
      "AABAAAAAAABCCC",
      "ABBBAAAAABCCCB",
      "AABBAAABCCCBAA",
      "AAAAABCCCCBAAA",
      "AAABCCCCBAAAAA",
      "AABCCCBAAAAAAA",
      "BCCCBAAAAAAAAA",
      "CCCBAAAAAAAAAA",
      "CBAAAAAAAAAAAA",
    ],
  },
  CF: {
    inks: { A: "#0000ff", B: "#ff0000", C: "#ffff00", D: "#ffffff", E: "#009a00" },
    rows: [
      "AAAAAABBAAAAAA",
      "ACAAAABBAAAAAA",
      "ADDAABBBBAAAAA",
      "DDDDDDBBDDDDDD",
      "DDDDDDBBDDDDDD",
      "EEEEEEBBEEEEEE",
      "EEEEEEBBEEEEEE",
      "EEEEEBBBBEEEEE",
      "CCCCCCBBCCCCCC",
      "CCCCCCBBCCCCCC",
    ],
  },
  CG: {
    inks: { A: "#00ca00", B: "#ffff00", C: "#ff0000" },
    rows: [
      "AAAAAAAAABBBBB",
      "AAAAAAAABBBBBC",
      "AAAAAAABBBBBCC",
      "AAAAAABBBBBCCC",
      "AAAAABBBBBCCCC",
      "AAAABBBBBCCCCC",
      "AAABBBBBCCCCCC",
      "AABBBBBCCCCCCC",
      "ABBBBBCCCCCCCC",
      "BBBBBCCCCCCCCC",
    ],
  },
  CH: {
    inks: { A: "#ff0000", B: "#ffffff" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAABBAAAAAA",
      "AAAAAABBAAAAAA",
      "AAAABBBBBBAAAA",
      "AAAABBBBBBAAAA",
      "AAAAAABBAAAAAA",
      "AAAAAABBAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
    ],
  },
  CI: {
    inks: { A: "#ff9a00", B: "#ffffff", C: "#00cd00" },
    rows: [
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
    ],
  },
  CL: {
    inks: { A: "#0039a6", B: "#ffffff", C: "#d52b1e" },
    rows: [
      "AAAAABBBBBBBBB",
      "AAAAABBBBBBBBB",
      "AABAABBBBBBBBB",
      "AAAAABBBBBBBBB",
      "AAAAABBBBBBBBB",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
    ],
  },
  CM: {
    inks: { A: "#007a5e", B: "#ce1126", C: "#fcd116" },
    rows: [
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
    ],
  },
  CN: {
    inks: { A: "#ee1c25", B: "#ffff00" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AABAAAAAAAAAAA",
      "ABBBAAAAAAAAAA",
      "AABAAABAAAAAAA",
      "AAAAABAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
    ],
  },
  CO: {
    inks: { A: "#ffe800", B: "#00148e", C: "#da0010" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
    ],
  },
  CR: {
    inks: { A: "#0000b4", B: "#ffffff", C: "#d90000" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "BBBBBBBBBBBBBB",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
      "BBBBBBBBBBBBBB",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
    ],
  },
  CU: {
    inks: { A: "#cb1515", B: "#002a8f", C: "#ffffff" },
    rows: [
      "ABBBBBBBBBBBBB",
      "AAABBBBBBBBBBB",
      "AAAAACCCCCCCCC",
      "AAAAAACCCCCCCC",
      "AACCAAAABBBBBB",
      "AACCAAAABBBBBB",
      "AAAAAACCCCCCCC",
      "AAAAACCCCCCCCC",
      "AAABBBBBBBBBBB",
      "ABBBBBBBBBBBBB",
    ],
  },
  CV: {
    inks: { A: "#081873", B: "#ffce08", C: "#ffffff", D: "#de3929" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAABAAAAAAA",
      "AAAAAAAAAAAAAA",
      "CCCCBCCCCCCCCC",
      "DDDDDDDDDDDDDD",
      "CCCCBCCCCCCCCC",
      "AAAAABBABAAAAA",
      "AAAAAAAAAAAAAA",
    ],
  },
  CY: {
    inks: { A: "#ffffff", B: "#d47600", C: "#435125" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAABAAAA",
      "AAAAABBBBAAAAA",
      "AAABBBBBBAAAAA",
      "AAABBBBAAAAAAA",
      "AAACAAAAACAAAA",
      "AAAACCACCAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
    ],
  },
  CZ: {
    inks: { A: "#11457e", B: "#ffffff", C: "#d7141a" },
    rows: [
      "ABBBBBBBBBBBBB",
      "AABBBBBBBBBBBB",
      "AAAABBBBBBBBBB",
      "AAAAAABBBBBBBB",
      "AAAAAAABBBBBBB",
      "AAAAAAACCCCCCC",
      "AAAAAACCCCCCCC",
      "AAAACCCCCCCCCC",
      "AACCCCCCCCCCCC",
      "ACCCCCCCCCCCCC",
    ],
  },
  DE: {
    inks: { A: "#000001", B: "#ff0000", C: "#ffcc00" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
    ],
  },
  DJ: {
    inks: { A: "#fffefe", B: "#6699ff", C: "#ff0000", D: "#00cc00" },
    rows: [
      "ABBBBBBBBBBBBB",
      "AABBBBBBBBBBBB",
      "AAAABBBBBBBBBB",
      "AAAAAABBBBBBBB",
      "AACAAAABBBBBBB",
      "AACAAAADDDDDDD",
      "AAAAAADDDDDDDD",
      "AAAADDDDDDDDDD",
      "AADDDDDDDDDDDD",
      "ADDDDDDDDDDDDD",
    ],
  },
  DK: {
    inks: { A: "#c8102e", B: "#ffffff" },
    rows: [
      "AAAABBAAAAAAAA",
      "AAAABBAAAAAAAA",
      "AAAABBAAAAAAAA",
      "AAAABBAAAAAAAA",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "AAAABBAAAAAAAA",
      "AAAABBAAAAAAAA",
      "AAAABBAAAAAAAA",
      "AAAABBAAAAAAAA",
    ],
  },
  DM: {
    inks: { A: "#108c00", B: "#ffd600", C: "#000001", D: "#ffffff", E: "#e72910" },
    rows: [
      "AAAAABCDDAAAAA",
      "AAAAABCDDAAAAA",
      "AAAAABEEAAAAAA",
      "BBBBBEEEEEBBBB",
      "CCCCEEEEEECCCC",
      "DDDDEEEAEEDDDD",
      "DDDDAEEEEEDDDD",
      "AAAAABEEAAAAAA",
      "AAAAABCDDAAAAA",
      "AAAAABCDDAAAAA",
    ],
  },
  DO: {
    inks: { A: "#002d62", B: "#ffffff", C: "#ce1126" },
    rows: [
      "AAAAAABBCCCCCC",
      "AAAAAABBCCCCCC",
      "AAAAAABBCCCCCC",
      "AAAAAABBCCCCCC",
      "BBBBBBBBBBBBBB",
      "BBBBBBBABBBBBB",
      "CCCCCCBBAAAAAA",
      "CCCCCCBBAAAAAA",
      "CCCCCCBBAAAAAA",
      "CCCCCCBBAAAAAA",
    ],
  },
  DZ: {
    inks: { A: "#006233", B: "#ffffff", C: "#d21034" },
    rows: [
      "AAAAAAABBBBBBB",
      "AAAAAAABBBBBBB",
      "AAAAAACCBBBBBB",
      "AAAAACABBBBBBB",
      "AAAACCACCBBBBB",
      "AAAACCACCBBBBB",
      "AAAAACABBBBBBB",
      "AAAAAACCBBBBBB",
      "AAAAAAABBBBBBB",
      "AAAAAAABBBBBBB",
    ],
  },
  EC: {
    inks: { A: "#ffe800", B: "#984000", C: "#a7cfff", D: "#0000c4", E: "#ffffff", F: "#da0010", G: "#00148e", H: "#afff7b" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAABBBBBBAAAA",
      "AAAAAABBAAAAAA",
      "AAAABBCCBBAAAA",
      "AAAADEECFDAAAA",
      "GGGGDHCHFDGGGG",
      "GGGGDFCBFDGGGG",
      "GGGGFHBBFFGGGG",
      "FFFFFFDDFFFFFF",
      "FFFFFFFFFFFFFF",
    ],
  },
  EE: {
    inks: { A: "#1791ff", B: "#000001", C: "#ffffff" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
    ],
  },
  EG: {
    inks: { A: "#ce1126", B: "#ffffff", C: "#c09300", D: "#000001" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "BBBBBBBBBBBBBB",
      "BBBBBBCCBBBBBB",
      "BBBBBBCCBBBBBB",
      "BBBBBBBBBBBBBB",
      "DDDDDDDDDDDDDD",
      "DDDDDDDDDDDDDD",
      "DDDDDDDDDDDDDD",
    ],
  },
  ER: {
    inks: { A: "#be0027", B: "#239e46", C: "#f3e295", D: "#b4d7f4" },
    rows: [
      "ABBBBBBBBBBBBB",
      "AAAABBBBBBBBBB",
      "AAACACABBBBBBB",
      "AACACACAAABBBB",
      "ACAACACAAAAAAB",
      "ACAACACAAAAAAD",
      "AACACACAAADDDD",
      "AAACCAADDDDDDD",
      "AAAADDDDDDDDDD",
      "ADDDDDDDDDDDDD",
    ],
  },
  ES: {
    inks: { A: "#aa151b", B: "#f1bf00", C: "#cccccc" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBCCBBBBBBBB",
      "BBBACCBBBBBBBB",
      "BBBBCBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
    ],
  },
  ET: {
    inks: { A: "#298c08", B: "#ffc621", C: "#006bc6", D: "#ef2118" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "BBBBBCCCABBBBB",
      "BBBBBCCCCBBBBB",
      "BBBBCCCCCBBBBB",
      "BBBBBCCCCBBBBB",
      "DDDDDDDDDDDDDD",
      "DDDDDDDDDDDDDD",
      "DDDDDDDDDDDDDD",
    ],
  },
  FI: {
    inks: { A: "#ffffff", B: "#002f6c" },
    rows: [
      "AAAABBBAAAAAAA",
      "AAAABBBAAAAAAA",
      "AAAABBBAAAAAAA",
      "AAAABBBAAAAAAA",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "AAAABBBAAAAAAA",
      "AAAABBBAAAAAAA",
      "AAAABBBAAAAAAA",
      "AAAABBBAAAAAAA",
    ],
  },
  FJ: {
    inks: { A: "#ffffff", B: "#012169", C: "#c8102e", D: "#68bfe5", E: "#ffd100" },
    rows: [
      "ABBCBBADDDDDDD",
      "BAACAABDDDDDDD",
      "CCCCCCCDDDDDDD",
      "BAACAABDDDDDDD",
      "ABBCBBADDCEECD",
      "DDDDDDDDDAAAAD",
      "DDDDDDDDDCCCCD",
      "DDDDDDDDDAAADD",
      "DDDDDDDDDDDDDD",
      "DDDDDDDDDDDDDD",
    ],
  },
  FM: {
    inks: { A: "#6797d6", B: "#ffffff" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAABBAAAAAA",
      "AAAAAABBAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAABAAAAAABAAA",
      "AAABAAAAAABAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAABBAAAAAA",
      "AAAAAABBAAAAAA",
      "AAAAAAAAAAAAAA",
    ],
  },
  FR: {
    inks: { A: "#000091", B: "#ffffff", C: "#e1000f" },
    rows: [
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
    ],
  },
  GA: {
    inks: { A: "#36a100", B: "#ffe700", C: "#006dbc" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
    ],
  },
  GB: {
    inks: { A: "#c8102e", B: "#ffffff", C: "#012169" },
    rows: [
      "ABCCCBAABCCCAB",
      "BABBCBAABCBABB",
      "CCAABBAABAABCC",
      "BBBBBBAABBBBBB",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "BBBBBBAABBBBBB",
      "CCBBABAABBAACC",
      "BBABCBAABCBBAC",
      "BACCCBAABCCCBA",
    ],
  },
  GD: {
    inks: { A: "#ce1126", B: "#fcd116", C: "#007a5e" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AABBBBBBBBBBAA",
      "ACCBBBBBBBBCCA",
      "ACCCCBBBBCCCCA",
      "ACBCCCAACCCCCA",
      "ACBCCCAACCCCCA",
      "ACCCCBBBBCCCCA",
      "ACCBBBBBBBBCCA",
      "AABBBBBBBBBBAA",
      "AAAAAAAAAAAAAA",
    ],
  },
  GE: {
    inks: { A: "#ffffff", B: "#ff0000" },
    rows: [
      "AAAAAABBAAAAAA",
      "AAAAAABBAAAAAA",
      "AAAAAABBAAAAAA",
      "AAAAAABBAAAAAA",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "AAAAAABBAAAAAA",
      "AAAAAABBAAAAAA",
      "AAAAAABBAAAAAA",
      "AAAAAABBAAAAAA",
    ],
  },
  GH: {
    inks: { A: "#ce1126", B: "#fcd116", C: "#000001", D: "#006b3f" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "BBBBBBBBBBBBBB",
      "BBBBBBCCBBBBBB",
      "BBBBBBCCBBBBBB",
      "BBBBBBCCBBBBBB",
      "DDDDDDDDDDDDDD",
      "DDDDDDDDDDDDDD",
      "DDDDDDDDDDDDDD",
    ],
  },
  GM: {
    inks: { A: "#ff0000", B: "#ffffff", C: "#000099", D: "#009900" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "BBBBBBBBBBBBBB",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
      "BBBBBBBBBBBBBB",
      "DDDDDDDDDDDDDD",
      "DDDDDDDDDDDDDD",
      "DDDDDDDDDDDDDD",
    ],
  },
  GN: {
    inks: { A: "#ff0000", B: "#ffff00", C: "#009900" },
    rows: [
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
    ],
  },
  GQ: {
    inks: { A: "#3e9a00", B: "#0073ce", C: "#ffffff", D: "#e32118" },
    rows: [
      "AAAAAAAAAAAAAA",
      "BAAAAAAAAAAAAA",
      "BBAAAAAAAAAAAA",
      "BBBCCCCCCCCCCC",
      "BBBBCCCCCCCCCC",
      "BBBBCCCCCCCCCC",
      "BBBCCCCCCCCCCC",
      "BBDDDDDDDDDDDD",
      "BDDDDDDDDDDDDD",
      "DDDDDDDDDDDDDD",
    ],
  },
  GR: {
    inks: { A: "#0d5eaf", B: "#ffffff" },
    rows: [
      "AABBAAAAAAAAAA",
      "AABBAABBBBBBBB",
      "BBBBBBAAAAAAAA",
      "AABBAABBBBBBBB",
      "AABBAAAAAAAAAA",
      "AABBAAAAAAAAAA",
      "BBBBBBBBBBBBBB",
      "AAAAAAAAAAAAAA",
      "BBBBBBBBBBBBBB",
      "AAAAAAAAAAAAAA",
    ],
  },
  GT: {
    inks: { A: "#4997d0", B: "#ffffff" },
    rows: [
      "AAAAABBBBAAAAA",
      "AAAAABBBBAAAAA",
      "AAAAABBBBAAAAA",
      "AAAAABBBBAAAAA",
      "AAAAABBBBAAAAA",
      "AAAAABBBBAAAAA",
      "AAAAABBBBAAAAA",
      "AAAAABBBBAAAAA",
      "AAAAABBBBAAAAA",
      "AAAAABBBBAAAAA",
    ],
  },
  GW: {
    inks: { A: "#ce1126", B: "#fcd116", C: "#000001", D: "#009e49" },
    rows: [
      "AAAAABBBBBBBBB",
      "AAAAABBBBBBBBB",
      "AAAAABBBBBBBBB",
      "AAAAABBBBBBBBB",
      "ACCCABBBBBBBBB",
      "ACCAADDDDDDDDD",
      "AAAAADDDDDDDDD",
      "AAAAADDDDDDDDD",
      "AAAAADDDDDDDDD",
      "AAAAADDDDDDDDD",
    ],
  },
  GY: {
    inks: { A: "#000001", B: "#ffffff", C: "#399408", D: "#de2110", E: "#ffde08" },
    rows: [
      "ABCCCCCCCCCCCC",
      "DAEBCCCCCCCCCC",
      "DDAEEEBCCCCCCC",
      "DDDDAEEEBBCCCC",
      "DDDDDAEEEEEBBC",
      "DDDDDAEEEEEBBC",
      "DDDDAEEEBBCCCC",
      "DDAEEEBCCCCCCC",
      "DAEBCCCCCCCCCC",
      "ABCCCCCCCCCCCC",
    ],
  },
  HK: {
    inks: { A: "#ec1b2e", B: "#ffffff" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAABAAAAAAA",
      "AAAAAABBBAAAAA",
      "AAAABBBBBBAAAA",
      "AAAAABBBBAAAAA",
      "AAAAABBBBAAAAA",
      "AAAAABAABAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
    ],
  },
  HN: {
    inks: { A: "#18c3df", B: "#ffffff" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
    ],
  },
  HR: {
    inks: { A: "#ff0000", B: "#0093dd", C: "#ffffff", D: "#171796" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAABBBBAAAAA",
      "CCCCCAAAACCCCC",
      "CCCCCCAACCCCCC",
      "CCCCCACCACCCCC",
      "CCCCCCAACCCCCC",
      "DDDDDDDDDDDDDD",
      "DDDDDDDDDDDDDD",
      "DDDDDDDDDDDDDD",
    ],
  },
  HT: {
    inks: { A: "#00209f", B: "#ffffff", C: "#d21034" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAABBBBAAAAA",
      "CCCCCBCCBCCCCC",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
    ],
  },
  HU: {
    inks: { A: "#d43516", B: "#ffffff", C: "#388d00" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
    ],
  },
  ID: {
    inks: { A: "#e70011", B: "#ffffff" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
    ],
  },
  IE: {
    inks: { A: "#009a49", B: "#ffffff", C: "#ff7900" },
    rows: [
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
    ],
  },
  IL: {
    inks: { A: "#ffffff", B: "#0038b8" },
    rows: [
      "AAAAAAAAAAAAAA",
      "BBBBBBBBBBBBBB",
      "AAAAAAAAAAAAAA",
      "AAAAAABBAAAAAA",
      "AAAAABAABAAAAA",
      "AAAAABAABAAAAA",
      "AAAAAABBAAAAAA",
      "AAAAAAAAAAAAAA",
      "BBBBBBBBBBBBBB",
      "AAAAAAAAAAAAAA",
    ],
  },
  IN: {
    inks: { A: "#ff9933", B: "#ffffff", C: "#000088", D: "#128807" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "BBBBBBBBBBBBBB",
      "BBBBBBCCBBBBBB",
      "BBBBBBCCBBBBBB",
      "BBBBBBBBBBBBBB",
      "DDDDDDDDDDDDDD",
      "DDDDDDDDDDDDDD",
      "DDDDDDDDDDDDDD",
    ],
  },
  IQ: {
    inks: { A: "#ce1126", B: "#ffffff", C: "#007a3d", D: "#000001" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBCBBBB",
      "BBBBCCCBCCBBBB",
      "BBBBBBBBBBBBBB",
      "DDDDDDDDDDDDDD",
      "DDDDDDDDDDDDDD",
      "DDDDDDDDDDDDDD",
    ],
  },
  IR: {
    inks: { A: "#239f40", B: "#ffffff", C: "#da0000" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBBBCBBBBBB",
      "BBBBBBBBBBBBBB",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
    ],
  },
  IS: {
    inks: { A: "#003897", B: "#ffffff", C: "#d72828" },
    rows: [
      "AAAABCBAAAAAAA",
      "AAAABCBAAAAAAA",
      "AAAABCBAAAAAAA",
      "AAAABCBAAAAAAA",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
      "AAAABCBAAAAAAA",
      "AAAABCBAAAAAAA",
      "AAAABCBAAAAAAA",
      "AAAABCBAAAAAAA",
    ],
  },
  IT: {
    inks: { A: "#009246", B: "#ffffff", C: "#ce2b37" },
    rows: [
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
    ],
  },
  JM: {
    inks: { A: "#ffcc00", B: "#009900", C: "#000001" },
    rows: [
      "AABBBBBBBBBBAA",
      "CAABBBBBBBBAAC",
      "CCAAABBBBAAACC",
      "CCCCAABBAACCCC",
      "CCCCCAAAACCCCC",
      "CCCCCAAAACCCCC",
      "CCCCAABBAACCCC",
      "CCAAABBBBAAACC",
      "CAABBBBBBBBAAC",
      "AABBBBBBBBBBAA",
    ],
  },
  JO: {
    inks: { A: "#ff0000", B: "#000001", C: "#ffffff", D: "#009900" },
    rows: [
      "ABBBBBBBBBBBBB",
      "AAABBBBBBBBBBB",
      "AAAAABBBBBBBBB",
      "AAAAAAAACCCCCC",
      "AAAAAAAAACCCCC",
      "AAAAAAAAACCCCC",
      "AAAAAAAACCCCCC",
      "AAAAADDDDDDDDD",
      "AAADDDDDDDDDDD",
      "ADDDDDDDDDDDDD",
    ],
  },
  JP: {
    inks: { A: "#ffffff", B: "#bc002d" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAABBBBAAAAA",
      "AAAABBBBBBAAAA",
      "AAAABBBBBBAAAA",
      "AAAABBBBBBAAAA",
      "AAAABBBBBBAAAA",
      "AAAAABBBBAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
    ],
  },
  KE: {
    inks: { A: "#000001", B: "#bb0000", C: "#ffffff", D: "#006600" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAABBAAAAAA",
      "CCCCCCBBCCCCCC",
      "BBBBBABBABBBBB",
      "BBBBBABBABBBBB",
      "CCCCCCBBCCCCCC",
      "DDDDDDBBDDDDDD",
      "DDDDDDDDDDDDDD",
      "DDDDDDDDDDDDDD",
    ],
  },
  KG: {
    inks: { A: "#ff0000", B: "#ffff00" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAABBAAAAAA",
      "AAAAABBBBAAAAA",
      "AAAABBBBBBAAAA",
      "AAAABBBBBBAAAA",
      "AAAAABBBBAAAAA",
      "AAAAAABBAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
    ],
  },
  KH: {
    inks: { A: "#032ea1", B: "#e00025", C: "#ffffff" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBCCCCBBBBB",
      "BBBBCCCCCCBBBB",
      "BBBBCCCCCCBBBB",
      "BBBBAAAAAABBBB",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
    ],
  },
  KI: {
    inks: { A: "#e73e2d", B: "#fec74a", C: "#ffffff", D: "#005989" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAABBBAAAAA",
      "AAAAAABBAAAAAA",
      "AAAAAABBAAAAAA",
      "AAAAABBBBAAAAA",
      "CCAACCBBCCAACA",
      "DDDCDDCCDDCDDD",
      "CDCCCCCCDCCCDC",
      "CCDDCCDDCCDCCC",
      "DDDDDDDDDDDDDD",
    ],
  },
  KM: {
    inks: { A: "#239e46", B: "#ffff00", C: "#ffffff", D: "#be0027", E: "#3b5aa3" },
    rows: [
      "ABBBBBBBBBBBBB",
      "AABBBBBBBBBBBB",
      "AAAABCCCCCCCCC",
      "ACAAACCCCCCCCC",
      "ACAAAAACCCCCCC",
      "ACAAAAADDDDDDD",
      "ACAAADDDDDDDDD",
      "AAAAEDDDDDDDDD",
      "AAEEEEEEEEEEEE",
      "AEEEEEEEEEEEEE",
    ],
  },
  KN: {
    inks: { A: "#35a100", B: "#ffe900", C: "#000001", D: "#ffffff", E: "#c70000" },
    rows: [
      "AAAAAAAAAABCCC",
      "AAAAAAAAABCCCC",
      "AAAAAAABCCCCCC",
      "AAAAABCCCDDCBE",
      "AAAABCCCCCCEEE",
      "AABCCCCCCBEEEE",
      "BBCDDCCBEEEEEE",
      "CCCCCCBEEEEEEE",
      "CCCCBEEEEEEEEE",
      "CCCBEEEEEEEEEE",
    ],
  },
  KP: {
    inks: { A: "#3e5698", B: "#c60000", C: "#ffffff" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "BBBBCBBBBBBBBB",
      "BBCCCCBBBBBBBB",
      "BBCBBCCBBBBBBB",
      "BBCBBCCBBBBBBB",
      "BBCCCCBBBBBBBB",
      "BBBBCBBBBBBBBB",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
    ],
  },
  KR: {
    inks: { A: "#ffffff", B: "#000001", C: "#cd2e3a", D: "#0047a0" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AABBAAAAAABAAA",
      "AABBAACCAABBAA",
      "AABAACCCCAABAA",
      "AAAACCCCCCAAAA",
      "AAAADDDDDDAAAA",
      "AABAADDDDAABAA",
      "AABBAADDAABBAA",
      "AABBAAAAAABAAA",
      "AAAAAAAAAAAAAA",
    ],
  },
  KW: {
    inks: { A: "#000001", B: "#00d941", C: "#ffffff", D: "#f31830" },
    rows: [
      "ABBBBBBBBBBBBB",
      "AABBBBBBBBBBBB",
      "AAAABBBBBBBBBB",
      "AAAAACCCCCCCCC",
      "AAAAACCCCCCCCC",
      "AAAAACCCCCCCCC",
      "AAAAACCCCCCCCC",
      "AAAADDDDDDDDDD",
      "AADDDDDDDDDDDD",
      "ADDDDDDDDDDDDD",
    ],
  },
  KZ: {
    inks: { A: "#00abc2", B: "#ffec2d" },
    rows: [
      "AAAAAAAAAAAAAA",
      "ABAAAAAAAAAAAA",
      "ABAAAAABAAAAAA",
      "ABAAAABBBAAAAA",
      "ABAAAABBBAAAAA",
      "ABAABABBBABAAA",
      "ABAAAAAAAAAAAA",
      "ABAAAAAAAAAAAA",
      "ABAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
    ],
  },
  LA: {
    inks: { A: "#ce1126", B: "#002868", C: "#ffffff" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "BBBBBBAABBBBBB",
      "BBBBBCCCCBBBBB",
      "BBBBBCCCCBBBBB",
      "BBBBBCCCCBBBBB",
      "BBBBBCCCCBBBBB",
      "BBBBBBAABBBBBB",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
    ],
  },
  LB: {
    inks: { A: "#ee161f", B: "#ffffff", C: "#00a850" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "BBBBBBAABBBBBB",
      "BBBBBBCCBBBBBB",
      "BBBBBCCCCBBBBB",
      "BBBBBCCCCBBBBB",
      "BBBBBBCCBBBBBB",
      "BBBBBAACABBBBB",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
    ],
  },
  LC: {
    inks: { A: "#65cfff", B: "#ffffff", C: "#000001", D: "#ffce00" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAABBAAAAAA",
      "AAAAAACCAAAAAA",
      "AAAAABCCBAAAAA",
      "AAAAACCCCAAAAA",
      "AAAABCDDCBAAAA",
      "AAAABDDDDBAAAA",
      "AAAADDDDDDAAAA",
      "AAAAAAAAAAAAAA",
    ],
  },
  LI: {
    inks: { A: "#002b7f", B: "#000001", C: "#ffd83d", D: "#ce1126" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAABAAAAAAAAAA",
      "AACCCCAAAAAAAA",
      "AACBCAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "DDDDDDDDDDDDDD",
      "DDDDDDDDDDDDDD",
      "DDDDDDDDDDDDDD",
      "DDDDDDDDDDDDDD",
      "DDDDDDDDDDDDDD",
    ],
  },
  LK: {
    inks: { A: "#ffb700", B: "#005641", C: "#ff5b00", D: "#8d2029", E: "#000000" },
    rows: [
      "ABACAAAAAAAAAA",
      "ABBCADDDDDDDDA",
      "ABBCADDDDDDDDA",
      "ABBCADDDAEEDDA",
      "ABBCADDEAAADDA",
      "ABBCADDAAAAADA",
      "ABBCADDDADAADA",
      "ABBCADDDDDDDDA",
      "ABBCADDDDDDDDA",
      "ABACAAAAAAAAAA",
    ],
  },
  LR: {
    inks: { A: "#000066", B: "#cc0000", C: "#ffffff" },
    rows: [
      "AAAAABBBBBBBBB",
      "AAAAACCCCCCCCC",
      "AACAABBBBBBBBB",
      "AAAAACCCCCCCCC",
      "AAAAABBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "CCCCCCCCCCCCCC",
      "BBBBBBBBBBBBBB",
      "CCCCCCCCCCCCCC",
      "BBBBBBBBBBBBBB",
    ],
  },
  LS: {
    inks: { A: "#00209f", B: "#ffffff", C: "#000000", D: "#009543" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "BBBBBBBBBBBBBB",
      "BBBBBBCCBBBBBB",
      "BBBBBBCCBBBBBB",
      "BBBBBBCCBBBBBB",
      "DDDDDDDDDDDDDD",
      "DDDDDDDDDDDDDD",
      "DDDDDDDDDDDDDD",
    ],
  },
  LT: {
    inks: { A: "#fdb913", B: "#006a44", C: "#c1272d" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
    ],
  },
  LU: {
    inks: { A: "#ed2939", B: "#ffffff", C: "#00a1de" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
    ],
  },
  LV: {
    inks: { A: "#981e32", B: "#ffffff" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
    ],
  },
  LY: {
    inks: { A: "#e70013", B: "#000001", C: "#ffffff", D: "#239e46" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "BBBBBBBBBBBBBB",
      "BBBBBBCBCBBBBB",
      "BBBBBBCBCBBBBB",
      "BBBBBBBBBBBBBB",
      "DDDDDDDDDDDDDD",
      "DDDDDDDDDDDDDD",
      "DDDDDDDDDDDDDD",
    ],
  },
  MA: {
    inks: { A: "#c1272d", B: "#006233" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAABBAAAAAA",
      "AAAAAABBAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
    ],
  },
  MC: {
    inks: { A: "#f31830", B: "#ffffff" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
    ],
  },
  MD: {
    inks: { A: "#00319c", B: "#ffde00", C: "#de2110", D: "#a77b3b", E: "#ff0000", F: "#008f00", G: "#564dff" },
    rows: [
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAADBDDBDCCCC",
      "AAAADDEEDDCCCC",
      "AAAADEEEEDCCCC",
      "AAAAFGBBGDCCCC",
      "AAAAFDGGDDCCCC",
      "AAAAABDDECCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
    ],
  },
  ME: {
    inks: { A: "#d3ae3b", B: "#c40308", C: "#1d5e91", D: "#cb5822" },
    rows: [
      "AAAAAAAAAAAAAA",
      "ABBBBBBBBBBBBA",
      "ABBBBBBBBBBBBA",
      "ABBBABAABABBBA",
      "ABBBAACCAABBBA",
      "ABBBAACCABBBBA",
      "ABBBBBAADBBBBA",
      "ABBBBBAABBBBBA",
      "ABBBBBBBBBBBBA",
      "AAAAAAAAAAAAAA",
    ],
  },
  MG: {
    inks: { A: "#ffffff", B: "#fc3d32", C: "#007e3a" },
    rows: [
      "AAAAABBBBBBBBB",
      "AAAAABBBBBBBBB",
      "AAAAABBBBBBBBB",
      "AAAAABBBBBBBBB",
      "AAAAABBBBBBBBB",
      "AAAAACCCCCCCCC",
      "AAAAACCCCCCCCC",
      "AAAAACCCCCCCCC",
      "AAAAACCCCCCCCC",
      "AAAAACCCCCCCCC",
    ],
  },
  MH: {
    inks: { A: "#3b5aa3", B: "#e2ae57", C: "#ffffff" },
    rows: [
      "AAAAAAAAAAAAAB",
      "AAAAAAAAAAAABB",
      "AACCCAAAAABBBC",
      "AACCCCAAABBCCC",
      "AACCCCABBCCCCA",
      "AAACCABBCCAAAA",
      "AAAABBCCAAAAAA",
      "AAABCCAAAAAAAA",
      "AABCAAAAAAAAAA",
      "BCAAAAAAAAAAAA",
    ],
  },
  MK: {
    inks: { A: "#d20000", B: "#ffe600" },
    rows: [
      "ABBAAABBAAABBA",
      "AABBAABBAABBAA",
      "AAABBAAAABBAAA",
      "AAAAAAAAAAAAAA",
      "BBBBAABBAABBBB",
      "BBBBAABBAABBBB",
      "AAAAAAAAAAAAAA",
      "AAABBAAAABBAAA",
      "AABBAABBAABBAA",
      "ABBAAABBAAABBA",
    ],
  },
  ML: {
    inks: { A: "#009a00", B: "#ffff00", C: "#ff0000" },
    rows: [
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
    ],
  },
  MM: {
    inks: { A: "#fecb00", B: "#34b233", C: "#ffffff", D: "#ea2839" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "BBBBBBCCBBBBBB",
      "BBBBCCCCCCBBBB",
      "BBBBBCCCCBBBBB",
      "BBBBBCCCCBBBBB",
      "DDDDDCDDCDDDDD",
      "DDDDDDDDDDDDDD",
      "DDDDDDDDDDDDDD",
    ],
  },
  MN: {
    inks: { A: "#da2032", B: "#0066b3", C: "#ffd900" },
    rows: [
      "AAAAABBBBAAAAA",
      "AAAAABBBBAAAAA",
      "AACAABBBBAAAAA",
      "AACAABBBBAAAAA",
      "AACAABBBBAAAAA",
      "CCCCABBBBAAAAA",
      "CCCCABBBBAAAAA",
      "CCCCABBBBAAAAA",
      "AAAAABBBBAAAAA",
      "AAAAABBBBAAAAA",
    ],
  },
  MO: {
    inks: { A: "#00785e", B: "#fbd116", C: "#ffffff" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAABBAAAAAA",
      "AAAAAACCAAAAAA",
      "AAAAAACCAAAAAA",
      "AAAACCCCCCAAAA",
      "AAAAACCCCAAAAA",
      "AAAAAACCAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
    ],
  },
  MR: {
    inks: { A: "#cd2a3e", B: "#006233", C: "#ffc400" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "BBBBBBBBBBBBBB",
      "BBBBBBCCBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBCBBBBCBBBB",
      "BBBBBCCCCBBBBB",
      "BBBBBBBBBBBBBB",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
    ],
  },
  MT: {
    inks: { A: "#ffffff", B: "#cf142b" },
    rows: [
      "AAAAAAABBBBBBB",
      "AAAAAAABBBBBBB",
      "AAAAAAABBBBBBB",
      "AAAAAAABBBBBBB",
      "AAAAAAABBBBBBB",
      "AAAAAAABBBBBBB",
      "AAAAAAABBBBBBB",
      "AAAAAAABBBBBBB",
      "AAAAAAABBBBBBB",
      "AAAAAAABBBBBBB",
    ],
  },
  MU: {
    inks: { A: "#ee2737", B: "#151f6d", C: "#ffcd00", D: "#00a04d" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
      "DDDDDDDDDDDDDD",
      "DDDDDDDDDDDDDD",
      "DDDDDDDDDDDDDD",
    ],
  },
  MV: {
    inks: { A: "#d21034", B: "#007e3a", C: "#ffffff" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAABBBBBBBBAAA",
      "AAABBBBBBBBAAA",
      "AAABBBCBBBBAAA",
      "AAABBBCBBBBAAA",
      "AAABBBBBBBBAAA",
      "AAABBBBBBBBAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
    ],
  },
  MW: {
    inks: { A: "#000001", B: "#f41408", C: "#21873b" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAABBBBAAAAA",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
    ],
  },
  MX: {
    inks: { A: "#006847", B: "#ffffff", C: "#ce1126" },
    rows: [
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBCBCCCCC",
      "AAAAABBABCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
    ],
  },
  MY: {
    inks: { A: "#000066", B: "#cc0000", C: "#ffcc00", D: "#ffffff" },
    rows: [
      "AAAAAAABBBBBBB",
      "AAAAAAABBBBBBB",
      "ACAACAADDDDDDD",
      "ACAACAABBBBBBB",
      "AAAAAAABBBBBBB",
      "AAAAAAADDDDDDD",
      "DDDDDDDDDDDDDD",
      "BBBBBBBBBBBBBB",
      "DDDDDDDDDDDDDD",
      "DDDDDDDDDDDDDD",
    ],
  },
  MZ: {
    inks: { A: "#ff0000", B: "#009a00", C: "#000001", D: "#ffca00", E: "#ffffff" },
    rows: [
      "ABBBBBBBBBBBBB",
      "AABBBBBBBBBBBB",
      "AAABBBBBBBBBBB",
      "AAAAACCCCCCCCC",
      "AACDAACCCCCCCC",
      "AAEEAACCCCCCCC",
      "AAAAAECCCCCCCC",
      "AAADDDDDDDDDDD",
      "AADDDDDDDDDDDD",
      "ADDDDDDDDDDDDD",
    ],
  },
  NA: {
    inks: { A: "#3662a2", B: "#ffffff", C: "#c70000", D: "#ffe700", E: "#38a100" },
    rows: [
      "AAAAAAAAAABCCC",
      "AAADDAAAABCCCC",
      "AAADDAABCCCCCC",
      "AAAAABCCCCCCBE",
      "AAAABCCCCCBEEE",
      "AABCCCCCCBEEEE",
      "BBCCCCCBEEEEEE",
      "CCCCCCBEEEEEEE",
      "CCCCBEEEEEEEEE",
      "CCCBEEEEEEEEEE",
    ],
  },
  NE: {
    inks: { A: "#e05206", B: "#ffffff", C: "#0db02b" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "BBBBBBAABBBBBB",
      "BBBBBBAABBBBBB",
      "BBBBBBAABBBBBB",
      "BBBBBBBBBBBBBB",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
    ],
  },
  NG: {
    inks: { A: "#008753", B: "#ffffff" },
    rows: [
      "AAAAABBBBAAAAA",
      "AAAAABBBBAAAAA",
      "AAAAABBBBAAAAA",
      "AAAAABBBBAAAAA",
      "AAAAABBBBAAAAA",
      "AAAAABBBBAAAAA",
      "AAAAABBBBAAAAA",
      "AAAAABBBBAAAAA",
      "AAAAABBBBAAAAA",
      "AAAAABBBBAAAAA",
    ],
  },
  NI: {
    inks: { A: "#0067c6", B: "#ffffff" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
    ],
  },
  NL: {
    inks: { A: "#ae1c28", B: "#ffffff", C: "#21468b" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
    ],
  },
  NO: {
    inks: { A: "#ed2939", B: "#ffffff", C: "#002664" },
    rows: [
      "AAAABCBAAAAAAA",
      "AAAABCBAAAAAAA",
      "AAAABCBAAAAAAA",
      "AAAABCBAAAAAAA",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
      "AAAABCBAAAAAAA",
      "AAAABCBAAAAAAA",
      "AAAABCBAAAAAAA",
      "AAAABCBAAAAAAA",
    ],
  },
  NP: {
    inks: { A: "#000063", B: "#ce0000", C: "#ffffff" },
    rows: [
      "A             ",
      "BBA           ",
      "BBBB          ",
      "BCCBBA        ",
      "BBCBBBBA      ",
      "BBBA          ",
      "BCCBA         ",
      "BCCBBA        ",
      "BBBBBBA       ",
      "ABBBBBBA      ",
    ],
  },
  NR: {
    inks: { A: "#002170", B: "#ffb20d", C: "#ffffff" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "AACCCAAAAAAAAA",
      "AACCCAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
    ],
  },
  NZ: {
    inks: { A: "#ffffff", B: "#c8102e", C: "#00247d" },
    rows: [
      "AAABABACCCCCCC",
      "AAABAAACCCCCCC",
      "BBBBBBBCCCCCCC",
      "AAABAAACCCCCCC",
      "ABABAAACCCCCCC",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCBCCC",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
    ],
  },
  OM: {
    inks: { A: "#ef2d29", B: "#ffffff", C: "#009025" },
    rows: [
      "AAAABBBBBBBBBB",
      "ABAABBBBBBBBBB",
      "AAAABBBBBBBBBB",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAACCCCCCCCCC",
      "AAAACCCCCCCCCC",
      "AAAACCCCCCCCCC",
    ],
  },
  PA: {
    inks: { A: "#ffffff", B: "#db0000", C: "#0000ab" },
    rows: [
      "AAAAAAABBBBBBB",
      "AAAAAAABBBBBBB",
      "AAACCAABBBBBBB",
      "AAAAAAABBBBBBB",
      "AAAAAAABBBBBBB",
      "CCCCCCCAAAAAAA",
      "CCCCCCCAAAAAAA",
      "CCCCCCCAABBAAA",
      "CCCCCCCAAAAAAA",
      "CCCCCCCAAAAAAA",
    ],
  },
  PE: {
    inks: { A: "#d91023", B: "#ffffff" },
    rows: [
      "AAAAABBBBAAAAA",
      "AAAAABBBBAAAAA",
      "AAAAABBBBAAAAA",
      "AAAAABBBBAAAAA",
      "AAAAABBBBAAAAA",
      "AAAAABBBBAAAAA",
      "AAAAABBBBAAAAA",
      "AAAAABBBBAAAAA",
      "AAAAABBBBAAAAA",
      "AAAAABBBBAAAAA",
    ],
  },
  PG: {
    inks: { A: "#000001", B: "#ff0000", C: "#ffcc00", D: "#ffffff" },
    rows: [
      "ABBBBBBBBBBBBB",
      "AABBBBBBBCBBBB",
      "AAAABBBBCCCBBB",
      "AAADABBCCCCCBB",
      "AAAAAABBBBCCBB",
      "AADAAAAABBBBBB",
      "AAAAAAAAABBBBB",
      "AAADAAAAAAABBB",
      "AAAAAAAAAAAABB",
      "AAAAAAAAAAAAAB",
    ],
  },
  PH: {
    inks: { A: "#ffffff", B: "#0038a8", C: "#fcd116", D: "#ce1126" },
    rows: [
      "ABBBBBBBBBBBBB",
      "AAABBBBBBBBBBB",
      "AAAAABBBBBBBBB",
      "AAACAABBBBBBBB",
      "AACCCAAABBBBBB",
      "AACCCAAADDDDDD",
      "AAACAADDDDDDDD",
      "AAAAADDDDDDDDD",
      "AAADDDDDDDDDDD",
      "ADDDDDDDDDDDDD",
    ],
  },
  PK: {
    inks: { A: "#ffffff", B: "#0c590b" },
    rows: [
      "AAABBBBBBBBBBB",
      "AAABBBBBBBBBBB",
      "AAABBBBBBBBBBB",
      "AAABBABBBBBBBB",
      "AAABBABBBBBBBB",
      "AAABBABBBBBBBB",
      "AAABBAAAABBBBB",
      "AAABBBBBBBBBBB",
      "AAABBBBBBBBBBB",
      "AAABBBBBBBBBBB",
    ],
  },
  PL: {
    inks: { A: "#ffffff", B: "#dc143c" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
    ],
  },
  PS: {
    inks: { A: "#ed2e38", B: "#000000", C: "#ffffff", D: "#009639" },
    rows: [
      "ABBBBBBBBBBBBB",
      "AABBBBBBBBBBBB",
      "AAAABBBBBBBBBB",
      "AAAAACCCCCCCCC",
      "AAAAAACCCCCCCC",
      "AAAAAACCCCCCCC",
      "AAAAACCCCCCCCC",
      "AAAADDDDDDDDDD",
      "AADDDDDDDDDDDD",
      "ADDDDDDDDDDDDD",
    ],
  },
  PT: {
    inks: { A: "#006600", B: "#ff0000", C: "#ffff00", D: "#ffffff" },
    rows: [
      "AAAAAABBBBBBBB",
      "AAAAAABBBBBBBB",
      "AAAAAABBBBBBBB",
      "AAAACCCBBBBBBB",
      "AAACDDDCBBBBBB",
      "AAACCDDCBBBBBB",
      "AAAACBCCBBBBBB",
      "AAAAAABBBBBBBB",
      "AAAAAABBBBBBBB",
      "AAAAAABBBBBBBB",
    ],
  },
  PW: {
    inks: { A: "#4aadd6", B: "#ffde00" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAABBBBAAAAAA",
      "AAABBBBBBAAAAA",
      "AAABBBBBBAAAAA",
      "AAABBBBBBAAAAA",
      "AAABBBBBAAAAAA",
      "AAAAABBAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
    ],
  },
  PY: {
    inks: { A: "#d52b1e", B: "#ffffff", C: "#0038a8" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
    ],
  },
  QA: {
    inks: { A: "#ffffff", B: "#8d1b3d" },
    rows: [
      "AAAAABBBBBBBBB",
      "AAAAABBBBBBBBB",
      "AAAAABBBBBBBBB",
      "AAAAABBBBBBBBB",
      "AAAAABBBBBBBBB",
      "AAAAABBBBBBBBB",
      "AAAAABBBBBBBBB",
      "AAAAABBBBBBBBB",
      "AAAAABBBBBBBBB",
      "AAAAABBBBBBBBB",
    ],
  },
  RO: {
    inks: { A: "#00319c", B: "#ffde00", C: "#de2110" },
    rows: [
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
    ],
  },
  RS: {
    inks: { A: "#c6363c", B: "#edb92e", C: "#0c4076", D: "#ffffff" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAABBAAAAAAAA",
      "CCCABBACCCCCCC",
      "CCCDDADCCCCCCC",
      "CCCDDDDCCCCCCC",
      "CCCDDADCCCCCCC",
      "DDDBDBDDDDDDDD",
      "DDDDDDDDDDDDDD",
      "DDDDDDDDDDDDDD",
    ],
  },
  RU: {
    inks: { A: "#ffffff", B: "#0039a6", C: "#d52b1e" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
    ],
  },
  RW: {
    inks: { A: "#00a1de", B: "#fad201", C: "#20603d" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAABBAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
    ],
  },
  SA: {
    inks: { A: "#165d31", B: "#ffffff" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAABAAAAAA",
      "AAABBBBBBBBAAA",
      "AAABBBBBBBBAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAABAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
    ],
  },
  SB: {
    inks: { A: "#0000d6", B: "#ffffff", C: "#ffcc00", D: "#006000" },
    rows: [
      "AAAAAAAAAAAAAA",
      "ABAAABAAAAAAAA",
      "AAABAAAAAAAAAA",
      "ABAAABAAAAAACC",
      "ABAAABAAAACCCD",
      "AAAAAAAACCCDDD",
      "AAAAAACCCDDDDD",
      "AAAACCCDDDDDDD",
      "AACCDDDDDDDDDD",
      "CCDDDDDDDDDDDD",
    ],
  },
  SC: {
    inks: { A: "#003d88", B: "#fcd955", C: "#d92223", D: "#ffffff", E: "#007a39" },
    rows: [
      "AAAABBBBBCCCCC",
      "AAAABBBBCCCCCC",
      "AAABBBBCCCCCCC",
      "AAABBBCCCCCCCC",
      "AAABBCCCCCCDDD",
      "AABBCCCCCDDDDD",
      "AABCCCCDDDDDDD",
      "ABCCCDDDDDEEEE",
      "ACCDDDEEEEEEEE",
      "BEEEEEEEEEEEEE",
    ],
  },
  SD: {
    inks: { A: "#009a00", B: "#ff0000", C: "#ffffff", D: "#000001" },
    rows: [
      "ABBBBBBBBBBBBB",
      "AABBBBBBBBBBBB",
      "AAAABBBBBBBBBB",
      "AAAAACCCCCCCCC",
      "AAAAAACCCCCCCC",
      "AAAAAACCCCCCCC",
      "AAAAACCCCCCCCC",
      "AAAADDDDDDDDDD",
      "AADDDDDDDDDDDD",
      "ADDDDDDDDDDDDD",
    ],
  },
  SE: {
    inks: { A: "#005293", B: "#fecb00" },
    rows: [
      "AAAABBAAAAAAAA",
      "AAAABBAAAAAAAA",
      "AAAABBAAAAAAAA",
      "AAAABBAAAAAAAA",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "AAAABBAAAAAAAA",
      "AAAABBAAAAAAAA",
      "AAAABBAAAAAAAA",
      "AAAABBAAAAAAAA",
    ],
  },
  SG: {
    inks: { A: "#df0000", B: "#ffffff" },
    rows: [
      "AAAAAAAAAAAAAA",
      "ABAAAAAAAAAAAA",
      "ABAAAAAAAAAAAA",
      "ABAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
    ],
  },
  SI: {
    inks: { A: "#ffffff", B: "#0000bf", C: "#d50000" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AABBBAAAAAAAAA",
      "BBAABBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
    ],
  },
  SK: {
    inks: { A: "#ffffff", B: "#0b4ea2", C: "#ee1c25" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "BBBCCACBBBBBBB",
      "BBBCCACBBBBBBB",
      "BBBCCCCBBBBBBB",
      "BBBBBBBBBBBBBB",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
    ],
  },
  SL: {
    inks: { A: "#00cd00", B: "#ffffff", C: "#0000cd" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
    ],
  },
  SM: {
    inks: { A: "#ffffff", B: "#ffdd00", C: "#4fd46b", D: "#8fc753", E: "#65c7ff", F: "#19b6ef" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAABBCAAAAA",
      "AAAACDEECCAAAA",
      "FFFFCCDECCFFFF",
      "FFFFCCDDCCFFFF",
      "FFFFFFFFFFFFFF",
      "FFFFFFFFFFFFFF",
      "FFFFFFFFFFFFFF",
    ],
  },
  SN: {
    inks: { A: "#0b7226", B: "#ffff00", C: "#bc0000" },
    rows: [
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABAABCCCCC",
      "AAAAABAABCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
    ],
  },
  SO: {
    inks: { A: "#40a6ff", B: "#ffffff" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAABBBBAAAAA",
      "AAAAABBBBAAAAA",
      "AAAAABBBAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
    ],
  },
  SR: {
    inks: { A: "#377e3f", B: "#ffffff", C: "#b40a2d", D: "#ecc81d" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "BBBBBBBBBBBBBB",
      "CCCCCCCCCCCCCC",
      "CCCCCCDDCCCCCC",
      "CCCCCCDDCCCCCC",
      "CCCCCCCCCCCCCC",
      "BBBBBBBBBBBBBB",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
    ],
  },
  SS: {
    inks: { A: "#0f47af", B: "#000001", C: "#ffffff", D: "#fcdd09", E: "#da121a", F: "#078930" },
    rows: [
      "ABBBBBBBBBBBBB",
      "AAABBBBBBBBBBB",
      "AAAAABBBBBBBBB",
      "AAAAAACCCCCCCC",
      "AADDAAAAEEEEEE",
      "AADDAAAAEEEEEE",
      "AAAAAACCCCCCCC",
      "AAAAAFFFFFFFFF",
      "AAAFFFFFFFFFFF",
      "AFFFFFFFFFFFFF",
    ],
  },
  ST: {
    inks: { A: "#d21034", B: "#12ad2b", C: "#ffce00", D: "#000001" },
    rows: [
      "ABBBBBBBBBBBBB",
      "AABBBBBBBBBBBB",
      "AAABBBBBBBBBBB",
      "AAAACCCCCCCCCC",
      "AAAAACCDCCCDCC",
      "AAAAACCDCCCDCC",
      "AAAACCCCCCCCCC",
      "AAABBBBBBBBBBB",
      "AABBBBBBBBBBBB",
      "ABBBBBBBBBBBBB",
    ],
  },
  SV: {
    inks: { A: "#0f47af", B: "#ffffff" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBBBABBBBBB",
      "BBBBBBBBBBBBBB",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
    ],
  },
  SY: {
    inks: { A: "#007a3d", B: "#ffffff", C: "#ce1126", D: "#000000" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "BBBBBBBBBBBBBB",
      "BBCCBBCCBBCCBB",
      "BBCCBBCCBBCCBB",
      "BBBBBBBBBBBBBB",
      "DDDDDDDDDDDDDD",
      "DDDDDDDDDDDDDD",
      "DDDDDDDDDDDDDD",
    ],
  },
  SZ: {
    inks: { A: "#3e5eb9", B: "#ffd900", C: "#b10c0c", D: "#333333", E: "#000000", F: "#ffffff" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "BBBBBBBBBBBBBB",
      "CCCCCDEFFCCCCC",
      "CCCEEEEFFFCFCC",
      "CDCCEEEFFFCCDC",
      "CCCCCEEFFCCCCC",
      "BBBBBBBBBBBBBB",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
    ],
  },
  TD: {
    inks: { A: "#002664", B: "#fecb00", C: "#c60c30" },
    rows: [
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
      "AAAAABBBBCCCCC",
    ],
  },
  TG: {
    inks: { A: "#d80000", B: "#118600", C: "#ffffff", D: "#ffe300" },
    rows: [
      "AAAAAABBBBBBBB",
      "AAAAAABBBBBBBB",
      "AACCAADDDDDDDD",
      "AACCAADDDDDDDD",
      "AAAAAABBBBBBBB",
      "AAAAAABBBBBBBB",
      "DDDDDDDDDDDDDD",
      "DDDDDDDDDDDDDD",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
    ],
  },
  TH: {
    inks: { A: "#a51931", B: "#f4f5f8", C: "#2d2a4a" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "BBBBBBBBBBBBBB",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
      "BBBBBBBBBBBBBB",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
    ],
  },
  TJ: {
    inks: { A: "#cc0000", B: "#ffffff", C: "#f8c300", D: "#006600" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBCCCCBBBBB",
      "DDDDDDDDDDDDDD",
      "DDDDDDDDDDDDDD",
      "DDDDDDDDDDDDDD",
    ],
  },
  TL: {
    inks: { A: "#000001", B: "#cb000f", C: "#f8c00c", D: "#ffffff" },
    rows: [
      "ABBBBBBBBBBBBB",
      "AACBBBBBBBBBBB",
      "AAACCCBBBBBBBB",
      "AAAAACCCBBBBBB",
      "ADDAAACCCCBBBB",
      "ADDAAACCCCBBBB",
      "AAAAACCCBBBBBB",
      "AAACCCBBBBBBBB",
      "AACBBBBBBBBBBB",
      "ABBBBBBBBBBBBB",
    ],
  },
  TM: {
    inks: { A: "#00843d", B: "#d22630", C: "#ffc72c", D: "#ffffff", E: "#695537" },
    rows: [
      "AABBBAAAAAAAAA",
      "AABBBAAAAAAAAA",
      "AABCBAAADAAAAA",
      "AABBBAADAAAAAA",
      "AABBBAAAAAAAAA",
      "AABBBAAAAAAAAA",
      "AACEBAAAAAAAAA",
      "AABBBAAAAAAAAA",
      "AABDBAAAAAAAAA",
      "AABBBAAAAAAAAA",
    ],
  },
  TN: {
    inks: { A: "#e70013", B: "#ffffff" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAABBAAAAAA",
      "AAAAABBBBAAAAA",
      "AAAABABBBBAAAA",
      "AAAABABBBBAAAA",
      "AAAAABBBBAAAAA",
      "AAAAAABBAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
    ],
  },
  TO: {
    inks: { A: "#ffffff", B: "#c10000" },
    rows: [
      "AAAAAABBBBBBBB",
      "AABAAABBBBBBBB",
      "AABAAABBBBBBBB",
      "AAAAAABBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
    ],
  },
  TR: {
    inks: { A: "#e30a17", B: "#ffffff" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAABBAAAAAAAA",
      "AAABBAAAABAAAA",
      "AAABBAAAABBAAA",
      "AAAABBAAAAAAAA",
      "AAAAABBAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
    ],
  },
  TT: {
    inks: { A: "#ffffff", B: "#000001", C: "#e00000" },
    rows: [
      "ABBBACCCCCCCCC",
      "CABBBACCCCCCCC",
      "CCABBBACCCCCCC",
      "CCCABBBACCCCCC",
      "CCCCABBBACCCCC",
      "CCCCCABBBACCCC",
      "CCCCCCABBBACCC",
      "CCCCCCCABBBACC",
      "CCCCCCCCABBBAC",
      "CCCCCCCCCABBBA",
    ],
  },
  TV: {
    inks: { A: "#ffffff", B: "#012169", C: "#c8102e", D: "#009fca", E: "#fff40d" },
    rows: [
      "ABBCBBADDDDDDD",
      "BAACAABDDDDDDD",
      "CCCCCCCDDDDDED",
      "BAACAABDDDDDDD",
      "ABBCBBADDEDEDD",
      "DDDDDDDDDDDDED",
      "DDDDDDDDDDDEDD",
      "DDDDDDDDDDDDDD",
      "DDDDDDEEEEDDDD",
      "DDDDDDDDDDDDDD",
    ],
  },
  TW: {
    inks: { A: "#000095", B: "#ff0000", C: "#ffffff" },
    rows: [
      "AAAAAAAABBBBBB",
      "AAACCAAABBBBBB",
      "AAACCAAABBBBBB",
      "AAACCAAABBBBBB",
      "AAAAAAAABBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
    ],
  },
  TZ: {
    inks: { A: "#009900", B: "#ffff00", C: "#000001", D: "#0099ff" },
    rows: [
      "AAAAAAAAAABBCC",
      "AAAAAAAAABCCCC",
      "AAAAAAABCCCCCB",
      "AAAAAABCCCCCBD",
      "AAAABCCCCCBBDD",
      "AABBCCCCCBDDDD",
      "ABCCCCCBDDDDDD",
      "BCCCCCBDDDDDDD",
      "CCCCBDDDDDDDDD",
      "CCBBDDDDDDDDDD",
    ],
  },
  UA: {
    inks: { A: "#0057b8", B: "#ffd700" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
    ],
  },
  UG: {
    inks: { A: "#000001", B: "#ffe700", C: "#de3908", D: "#fffdff" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "BBBBBBBBBBBBBB",
      "CCCCCCDDCCCCCC",
      "CCCCCDDDDCCCCC",
      "AAAAADDDDAAAAA",
      "AAAAAADDAAAAAA",
      "BBBBBBBBBBBBBB",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
    ],
  },
  US: {
    inks: { A: "#192f5d", B: "#bd3d44", C: "#ffffff" },
    rows: [
      "AAAAAAAABBBBBB",
      "AAAAAAAACCCCCC",
      "AAAAAAAACCCCCC",
      "AAAAAAAABBBBBB",
      "AAAAAAAACCCCCC",
      "CCCCCCCCCCCCCC",
      "BBBBBBBBBBBBBB",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
      "BBBBBBBBBBBBBB",
    ],
  },
  UY: {
    inks: { A: "#ffffff", B: "#fcd116", C: "#0038a8" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AABBAACCCCCCCC",
      "ABBBBAAAAAAAAA",
      "ABBBAACCCCCCCC",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "CCCCCCCCCCCCCC",
      "AAAAAAAAAAAAAA",
      "CCCCCCCCCCCCCC",
      "AAAAAAAAAAAAAA",
    ],
  },
  UZ: {
    inks: { A: "#0099b5", B: "#ffffff", C: "#1eb53a" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
    ],
  },
  VA: {
    inks: { A: "#ffe000", B: "#ffffff" },
    rows: [
      "AAAAAAABBBBBBB",
      "AAAAAAABBBBBBB",
      "AAAAAAABBBBBBB",
      "AAAAAAABBBABBB",
      "AAAAAAABBBBBBB",
      "AAAAAAABBBBBBB",
      "AAAAAAABBBBBBB",
      "AAAAAAABBBBBBB",
      "AAAAAAABBBBBBB",
      "AAAAAAABBBBBBB",
    ],
  },
  VC: {
    inks: { A: "#0058aa", B: "#f4f100", C: "#199a00" },
    rows: [
      "AAABBBBBBBBCCC",
      "AAABBBBBBBBCCC",
      "AAABBBBBBBBCCC",
      "AAABBCBBCBBCCC",
      "AAABBCBCCBBCCC",
      "AAABBBCCBBBCCC",
      "AAABBBCCBBBCCC",
      "AAABBBBBBBBCCC",
      "AAABBBBBBBBCCC",
      "AAABBBBBBBBCCC",
    ],
  },
  VE: {
    inks: { A: "#ffcc00", B: "#00247d", C: "#cf142b" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
    ],
  },
  VN: {
    inks: { A: "#da251d", B: "#ffff00" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAABBAAAAAA",
      "AAAAABBBBBAAAA",
      "AAAAAABBBAAAAA",
      "AAAAABBBBAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
    ],
  },
  VU: {
    inks: { A: "#000000", B: "#d21034", C: "#fdce12", D: "#009543" },
    rows: [
      "ABBBBBBBBBBBBB",
      "CABBBBBBBBBBBB",
      "AACABBBBBBBBBB",
      "AAACCABBBBBBBB",
      "AAAAACAAAAAAAA",
      "AACAACAAAAAAAA",
      "AAACCADDDDDDDD",
      "AACADDDDDDDDDD",
      "CADDDDDDDDDDDD",
      "ADDDDDDDDDDDDD",
    ],
  },
  WS: {
    inks: { A: "#002b7f", B: "#ffffff", C: "#ce1126" },
    rows: [
      "AAABAAACCCCCCC",
      "AAAAAAACCCCCCC",
      "AAAAAAACCCCCCC",
      "AAAAAAACCCCCCC",
      "AAABAAACCCCCCC",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
    ],
  },
  XK: {
    inks: { A: "#244aa5", B: "#ffffff", C: "#d0a650" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAABBABBABBAAA",
      "AAAAAACCAAAAAA",
      "AAAAAACCCAAAAA",
      "AAAACCCCCCAAAA",
      "AAAAACCCCAAAAA",
      "AAAAAACAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
    ],
  },
  YE: {
    inks: { A: "#f10600", B: "#ffffff", C: "#000001" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAA",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
      "CCCCCCCCCCCCCC",
    ],
  },
  ZA: {
    inks: { A: "#007847", B: "#ffffff", C: "#e1392d", D: "#ffb915", E: "#000001", F: "#000c8a" },
    rows: [
      "AAABCCCCCCCCCC",
      "DAAABBCCCCCCCC",
      "EDAAAABCCCCCCC",
      "EEDDAAABBBBBBB",
      "EEEEDAAAAAAAAA",
      "EEEEDAAAAAAAAA",
      "EEDDAAABBBBBBB",
      "EDAAAABFFFFFFF",
      "DAAABBFFFFFFFF",
      "AAABFFFFFFFFFF",
    ],
  },
  ZM: {
    inks: { A: "#198a00", B: "#ef7d00", C: "#de2010", D: "#000001" },
    rows: [
      "AAAAAAAAAAAAAA",
      "AAAAAAAAABBBBB",
      "AAAAAAAAAAABAA",
      "AAAAAAAAACADBB",
      "AAAAAAAACCDDBB",
      "AAAAAAAACCDDBB",
      "AAAAAAAACCDDBB",
      "AAAAAAAACCDDBB",
      "AAAAAAAACCDDBB",
      "AAAAAAAACCDDBB",
    ],
  },
  ZW: {
    inks: { A: "#ffffff", B: "#006400", C: "#ffd200", D: "#d40000", E: "#000001" },
    rows: [
      "ABBBBBBBBBBBBB",
      "AABCCCCCCCCCCC",
      "AAAACCCCCCCCCC",
      "AADAADDDDDDDDD",
      "ADCDAAEEEEEEEE",
      "AACDAAEEEEEEEE",
      "AAAAADDDDDDDDD",
      "AAAACCCCCCCCCC",
      "AABCCCCCCCCCCC",
      "ABBBBBBBBBBBBB",
    ],
  },
};
