// Hand-drawn 14×10 flags for countries whose emblems are too fine to survive sampling the emoji down (stars, script,
// seals). Each row is a string of letters; `inks` gives each letter's colour. These are the flags' own colours, as
// content, not interface colours, so they don't come from the design tokens. The corner cells are cut by the mask.

export type FlagArt = { rows: string[]; inks: Record<string, string> };

export const FLAG_ART: Record<string, FlagArt> = {
  // the white bauhinia, five petals swirling round the centre
  HK: {
    inks: { R: "#de2910", W: "#ffffff" },
    rows: [
      "RRRRRRRRRRRRRR",
      "RRRRRRWWRRRRRR",
      "RRRRRRWWRWRRRR",
      "RRRRWRRWWWRRRR",
      "RRRWWWRWWRRRRR",
      "RRRRRWWRWWWRRR",
      "RRRRWWWRRWRRRR",
      "RRRRWRWWRRRRRR",
      "RRRRRRWWRRRRRR",
      "RRRRRRRRRRRRRR",
    ],
  },
  CN: {
    inks: { R: "#de2910", Y: "#ffde00" },
    rows: [
      "RRRRRRRRRRRRRR",
      "RRRYRRRYRRRRRR",
      "RYYYYYRRRYRRRR",
      "RRYYYRRRRRRRRR",
      "RRYRYRRRRYRRRR",
      "RRRRRRRYRRRRRR",
      "RRRRRRRRRRRRRR",
      "RRRRRRRRRRRRRR",
      "RRRRRRRRRRRRRR",
      "RRRRRRRRRRRRRR",
    ],
  },
  KR: {
    inks: { W: "#ffffff", K: "#000000", R: "#cd2e3a", B: "#0047a0" },
    rows: [
      "WWWWWWWWWWWWWW",
      "WKWWWWWWWWWWKW",
      "WWKWWWWWWWWKWW",
      "WWWWWWRRWWWWWW",
      "WWWWWRRRBWWWWW",
      "WWWWWRBBBWWWWW",
      "WWWWWWBBWWWWWW",
      "WWKWWWWWWWWKWW",
      "WKWWWWWWWWWWKW",
      "WWWWWWWWWWWWWW",
    ],
  },
  SA: {
    inks: { G: "#006c35", W: "#ffffff" },
    rows: [
      "GGGGGGGGGGGGGG",
      "GGGGGGGGGGGGGG",
      "GGWGGWGWGGWGGG",
      "GGWWWWWWWWWGGG",
      "GGGGGGGGGGGGGG",
      "GGGWWWWWWWWGGG",
      "GGGGGGGGGGWGGG",
      "GGGGGGGGGGGGGG",
      "GGGGGGGGGGGGGG",
      "GGGGGGGGGGGGGG",
    ],
  },
  AF: {
    inks: { K: "#000000", R: "#be0000", G: "#007a36", W: "#ffffff" },
    rows: [
      "KKKKKRRRRGGGGG",
      "KKKKKRRRRGGGGG",
      "KKKKKRRRRGGGGG",
      "KKKKKRWWRGGGGG",
      "KKKKKWRRWGGGGG",
      "KKKKKWRRWGGGGG",
      "KKKKKRWWRGGGGG",
      "KKKKKRRRRGGGGG",
      "KKKKKRRRRGGGGG",
      "KKKKKRRRRGGGGG",
    ],
  },
  TM: {
    inks: { G: "#00843d", C: "#d22630", Y: "#ffc72c", W: "#ffffff" },
    rows: [
      "GGCCCGGGGGGGGG",
      "GGCYCGGWWGWGGG",
      "GGCCCGWGGGGGGG",
      "GGCYCGGWWGWGGG",
      "GGCCCGGGGGGGGG",
      "GGCYCGGGGGGGGG",
      "GGCCCGGGGGGGGG",
      "GGCYCGGGGGGGGG",
      "GGCCCGGGGGGGGG",
      "GGCYCGGGGGGGGG",
    ],
  },
  KZ: {
    inks: { B: "#00afca", Y: "#fec50c" },
    rows: [
      "BBBBBBBBBBBBBB",
      "BYBBBYBYBYBBBB",
      "BBYBBBYYYBBBBB",
      "BYBBBYYYYYBBBB",
      "BBYBBBYYYBBBBB",
      "BYBBBYBYBYBBBB",
      "BBYBYYBBBYYBBB",
      "BYBBBYYYYYBBBB",
      "BBYBBBBBBBBBBB",
      "BBBBBBBBBBBBBB",
    ],
  },
  KG: {
    inks: { R: "#e8112d", Y: "#ffef00" },
    rows: [
      "RRRRRRRRRRRRRR",
      "RRRRYRYYRYRRRR",
      "RRRRRYYYYRRRRR",
      "RRRYYYRRYYYRRR",
      "RRRRYRYYRYRRRR",
      "RRRRYRYYRYRRRR",
      "RRRYYYRRYYYRRR",
      "RRRRRYYYYRRRRR",
      "RRRRYRYYRYRRRR",
      "RRRRRRRRRRRRRR",
    ],
  },
  TR: {
    inks: { R: "#e30a17", W: "#ffffff" },
    rows: [
      "RRRRRRRRRRRRRR",
      "RRRRRRRRRRRRRR",
      "RRRWWWRRRRRRRR",
      "RRWWRRRRRWRRRR",
      "RWWRRRRRWWWRRR",
      "RWWRRRRRWRWRRR",
      "RRWWRRRRRRRRRR",
      "RRRWWWRRRRRRRR",
      "RRRRRRRRRRRRRR",
      "RRRRRRRRRRRRRR",
    ],
  },
  MY: {
    inks: { B: "#010066", Y: "#ffcc00", R: "#cc0001", W: "#ffffff" },
    rows: [
      "BBBBBBBRRRRRRR",
      "BBYYBBBWWWWWWW",
      "BYBBBYBRRRRRRR",
      "BBYYBBBWWWWWWW",
      "BBBBBBBRRRRRRR",
      "WWWWWWWWWWWWWW",
      "RRRRRRRRRRRRRR",
      "WWWWWWWWWWWWWW",
      "RRRRRRRRRRRRRR",
      "WWWWWWWWWWWWWW",
    ],
  },
};
