import { chromium } from "playwright";
const U = process.argv[2]; const S = process.env.SHOTS;
const b = await chromium.launch(); const c = await b.newContext(); const p = await c.newPage();
p.on("console", m => { if (m.type()==="error"||m.type()==="warning") console.log("console", m.type(), m.text().slice(0,200)); });
p.on("requestfailed", r => console.log("failed", r.url().slice(0,120), r.failure()?.errorText));
p.on("response", r => { if (r.status()>=400) console.log("http", r.status(), r.url().slice(0,120)); });
await p.goto(U + "/", { waitUntil: "networkidle", timeout: 60000 }).catch(e => console.log("goto:", e.message.slice(0,100)));
await p.waitForTimeout(4000);
console.log("title:", await p.title(), "| body text:", (await p.locator("body").innerText()).replace(/\s+/g," ").slice(0,200));
if (S) await p.screenshot({ path: `${S}/tunnel-home.png` });
await p.goto(U + "/t/demo6s08zg82vkrc", { waitUntil: "networkidle", timeout: 60000 }).catch(e => console.log("goto:", e.message.slice(0,100)));
await p.waitForTimeout(4000);
console.log("trip body:", (await p.locator("body").innerText()).replace(/\s+/g," ").slice(0,200));
if (S) await p.screenshot({ path: `${S}/tunnel-trip.png` });
await b.close();
