// Builds the cities printed on the globe from Natural Earth 10m populated places.
// Run with `pnpm cities`. Downloads the source once into .cache/, then writes src/components/trip-globe/cities.ts.
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const MAX_RANK = 7; // Natural Earth scalerank: 0 world cities … 10 small towns. Up to 7 is about 4,000 places.

// Pinned, so the list rebuilds the same way.
const NE_COMMIT = "ca96624a56bd078437bca8184e78163e5039ad19";
const NE_FILE = "ne_10m_populated_places_simple.geojson";
const SOURCE = `https://raw.githubusercontent.com/nvkelso/natural-earth-vector/${NE_COMMIT}/geojson/${NE_FILE}`;
const CACHE = fileURLToPath(new URL(`../.cache/natural-earth/${NE_COMMIT}/`, import.meta.url));
const TS_OUT = fileURLToPath(new URL("../src/components/trip-globe/cities.ts", import.meta.url));

interface Feature {
  properties: { name: string; scalerank: number; adm0cap: number; latitude: number; longitude: number; pop_max: number };
}

const file = CACHE + NE_FILE;
if (!existsSync(file)) {
  console.log(`Downloading ${SOURCE}`);
  const response = await fetch(SOURCE);
  if (!response.ok) throw new Error(`Natural Earth returned ${response.status}`);
  mkdirSync(CACHE, { recursive: true });
  writeFileSync(file, Buffer.from(await response.arrayBuffer()));
}
const { features } = JSON.parse(readFileSync(file, "utf8")) as { features: Feature[] };

const round = (x: number) => Math.round(x * 100) / 100;
const cities = features
  .map((f) => f.properties)
  .filter((p) => p.name && p.scalerank <= MAX_RANK)
  // biggest first: the order names win a place on screen
  .sort((a, b) => a.scalerank - b.scalerank || b.adm0cap - a.adm0cap || b.pop_max - a.pop_max)
  .map((p) => [p.name, round(p.latitude), round(p.longitude), p.scalerank, p.adm0cap ? 1 : 0] as const);

writeFileSync(
  TS_OUT,
  `// Generated by scripts/build-cities.mts from Natural Earth 10m populated places. Do not edit.
// The cities printed on the globe, biggest first: [name, lat, lng, rank (0 world city … ${MAX_RANK}), capital (1 or 0)].

export type CityLabel = readonly [name: string, lat: number, lng: number, rank: number, capital: 0 | 1];

export const CITY_LABELS: readonly CityLabel[] = [
${cities.map((c) => `  ${JSON.stringify(c)},`).join("\n")}
];
`,
);
console.log(`Wrote ${cities.length} cities to cities.ts`);
