// Downloads GTFS feeds into .cache/gtfs/ and writes per-city-pair JSON for the gtfs provider.
// Run with `pnpm gtfs:build` (`--fresh` re-downloads). Never runs at request time.
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { strFromU8, unzipSync } from "fflate";
import {
  NEEDED_FILES,
  assertFeedCurrent,
  buildPairs,
  feedCalendar,
  mergePairs,
  readFeed,
} from "../src/lib/transport/providers/gtfs/build.ts";
import type { City, FeedMeta, GtfsMeta, PairFile } from "../src/lib/transport/providers/gtfs/schema.ts";

interface FeedSource extends Omit<FeedMeta, "version" | "calendarStart" | "calendarEnd"> {
  routeTypes: number[];
}

// data.gov.my feeds are 4 req/min: keep downloads sequential. KTMB calendar is short (~2 months): assertFeedCurrent fails the build once it lapses.
const FEEDS: FeedSource[] = [
  {
    id: "namtang",
    name: "Thailand OTP namtang",
    url: "https://namtang-api.otp.go.th/download/namtang-gtfs.zip",
    country: "TH",
    licence: "CC BY 4.0",
    attribution: "Data: Office of Transport and Traffic Policy and Planning (OTP), Thailand, CC BY 4.0",
    routeTypes: [2, 3],
  },
  {
    id: "ktmb",
    name: "KTMB (Keretapi Tanah Melayu)",
    url: "https://api.data.gov.my/gtfs-static/ktmb",
    country: "MY",
    licence: "CC BY 4.0",
    attribution: "Data: KTMB via data.gov.my, CC BY 4.0",
    routeTypes: [2],
  },
];

const ROOT = fileURLToPath(new URL("../", import.meta.url));
const CACHE = `${ROOT}.cache/gtfs/`;
const OUT = `${ROOT}src/lib/transport/providers/gtfs/`;
const PAIRS = `${OUT}pairs/`;
const MAX_AGE_MS = 24 * 3600 * 1000;
const fresh = process.argv.includes("--fresh");

async function download(feed: FeedSource): Promise<Uint8Array> {
  const file = `${CACHE}${feed.id}.zip`;
  if (!fresh && existsSync(file) && Date.now() - statSync(file).mtimeMs < MAX_AGE_MS) {
    console.log(`${feed.id}: cached ${file}`);
    return readFileSync(file);
  }
  console.log(`${feed.id}: downloading ${feed.url}`);
  const res = await fetch(feed.url, { signal: AbortSignal.timeout(300_000) });
  if (!res.ok) throw new Error(`${feed.id}: HTTP ${res.status}`);
  const buf = new Uint8Array(await res.arrayBuffer());
  writeFileSync(file, buf);
  return buf;
}

mkdirSync(CACHE, { recursive: true });
const cities = JSON.parse(readFileSync(`${OUT}cities.json`, "utf8")) as City[];
const today = new Date().toISOString().slice(0, 10).replaceAll("-", "");
const all: Record<string, PairFile> = {};
const feedsMeta: FeedMeta[] = [];

for (const src of FEEDS) {
  const needed = new Set<string>(NEEDED_FILES);
  const entries = unzipSync(await download(src), { filter: (f) => needed.has(f.name) });
  const files = Object.fromEntries(Object.entries(entries).map(([name, data]) => [name, strFromU8(data)]));
  const feed = readFeed(files);
  assertFeedCurrent(src.id, feed, today);
  const cal = feedCalendar(feed);
  const { routeTypes, ...meta } = src;
  feedsMeta.push({
    ...meta,
    ...(feed.feedInfo[0]?.feed_version ? { version: feed.feedInfo[0].feed_version } : {}),
    calendarStart: cal.start,
    calendarEnd: cal.end,
  });
  const pairs = buildPairs(feed, { feedId: src.id, cities, routeTypes });
  console.log(`${src.id}: ${Object.keys(pairs).length} pairs`);
  mergePairs(all, pairs);
}

mkdirSync(PAIRS, { recursive: true });
for (const f of readdirSync(PAIRS)) if (f.endsWith(".json")) rmSync(`${PAIRS}${f}`);
const keys = Object.keys(all).sort();
for (const key of keys) writeFileSync(`${PAIRS}${key}.json`, `${JSON.stringify(all[key])}\n`);

const loaders = keys
  .map((key) => `  "${key}": () => import("./${key}.json").then((m) => m.default as unknown as PairFile),`)
  .join("\n");
writeFileSync(
  `${PAIRS}index.ts`,
  `// Generated by scripts/gtfs-build.mts. Do not edit.\nimport type { PairFile } from "../schema";\n\nexport const pairs: Record<string, () => Promise<PairFile>> = {\n${loaders}\n};\n`,
);

const meta: GtfsMeta = { builtAt: new Date().toISOString(), feeds: feedsMeta, pairs: keys };
writeFileSync(`${OUT}meta.json`, `${JSON.stringify(meta, null, 2)}\n`);
const departures = keys.reduce((n, k) => n + all[k].departures.length, 0);
console.log(`wrote ${keys.length} pair files, ${departures} departures`);
