// Independent, official KTMB refresh. No key, scraper, runtime dependency, commit or publish.
// node scripts/refresh-ktmb.mts [--check] [--min-days=7]
import { mkdirSync, readFileSync, renameSync, rmSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { createHash } from "node:crypto";
import { strFromU8, unzipSync } from "fflate";
import { NEEDED_FILES, assertFeedCurrent, buildPairs, feedCalendar, readFeed } from "../src/lib/transport/providers/gtfs/build.ts";
import { assertHorizon, replaceFeedPairs } from "../src/lib/transport/providers/gtfs/refresh.ts";
import type { City, GtfsMeta, PairFile } from "../src/lib/transport/providers/gtfs/schema.ts";

const root = fileURLToPath(new URL("../", import.meta.url));
const out = `${root}src/lib/transport/providers/gtfs/`;
const meta = JSON.parse(readFileSync(`${out}meta.json`, "utf8")) as GtfsMeta;
const today = new Date().toISOString().slice(0, 10).replaceAll("-", "");
const minDays = Number(process.argv.find((arg) => arg.startsWith("--min-days="))?.split("=")[1] ?? 7);
const previous = meta.feeds.find((feed) => feed.id === "ktmb");
if (!previous) throw new Error("Bundled KTMB metadata missing");
if (process.argv.includes("--check")) {
  console.log(`KTMB: ${assertHorizon(previous.calendarEnd, today, minDays)} days remaining; built ${meta.builtAt}`);
} else {
  const url = "https://api.data.gov.my/gtfs-static/ktmb";
  const res = await fetch(url, { signal: AbortSignal.timeout(8_000) });
  if (!res.ok) throw new Error(`KTMB HTTP ${res.status}; bundled snapshot unchanged`);
  const bytes = new Uint8Array(await res.arrayBuffer());
  const needed = new Set<string>(NEEDED_FILES);
  const entries = unzipSync(bytes, { filter: (file) => needed.has(file.name) });
  const feed = readFeed(Object.fromEntries(Object.entries(entries).map(([name, value]) => [name, strFromU8(value)])));
  assertFeedCurrent("ktmb", feed, today);
  const calendar = feedCalendar(feed);
  const daysRemaining = assertHorizon(calendar.end, today, minDays);
  const cities = JSON.parse(readFileSync(`${out}cities.json`, "utf8")) as City[];
  const incoming = buildPairs(feed, { feedId: "ktmb", cities, routeTypes: [2] });
  // A valid ZIP containing no usable rail must not erase the last good snapshot.
  if (!Object.keys(incoming).length) throw new Error("KTMB returned no usable rail pairs; snapshot unchanged");
  const existing = Object.fromEntries(meta.pairs.map((key) => [key, JSON.parse(readFileSync(`${out}pairs/${key}.json`, "utf8")) as PairFile]));
  const pairs = replaceFeedPairs(existing, incoming, "ktmb");
  const keys = Object.keys(pairs).sort();
  const fetchedAt = new Date().toISOString();
  const updated: GtfsMeta = {
    ...meta, builtAt: fetchedAt, pairs: keys,
    feeds: meta.feeds.map((item) => item.id !== "ktmb" ? item : {
      ...item, licence: "CC BY 4.0", attribution: "Data: KTMB via data.gov.my, CC BY 4.0",
      calendarStart: calendar.start, calendarEnd: calendar.end, refreshedAt: fetchedAt,
    }),
  };
  // Complete download, parse, validation and staging before replacing any bundled data.
  const staging = `${root}.cache/ktmb-refresh/`;
  mkdirSync(staging, { recursive: true });
  for (const key of keys) writeFileSync(`${staging}${key}.json`, `${JSON.stringify(pairs[key])}\n`);
  const loaders = keys.map((key) => `  "${key}": () => import("./${key}.json").then((m) => m.default as unknown as PairFile),`).join("\n");
  writeFileSync(`${staging}index.ts`, `// Generated by scripts/gtfs-build.mts or scripts/refresh-ktmb.mts. Do not edit.\nimport type { PairFile } from "../schema";\n\nexport const pairs: Record<string, () => Promise<PairFile>> = {\n${loaders}\n};\n`);
  writeFileSync(`${staging}meta.json`, `${JSON.stringify(updated, null, 2)}\n`);
  for (const key of keys) renameSync(`${staging}${key}.json`, `${out}pairs/${key}.json`);
  renameSync(`${staging}index.ts`, `${out}pairs/index.ts`);
  renameSync(`${staging}meta.json`, `${out}meta.json`);
  for (const key of meta.pairs) if (!keys.includes(key)) rmSync(`${out}pairs/${key}.json`);
  const report = { source: url, fetchedAt, sha256: createHash("sha256").update(bytes).digest("hex"), calendar, daysRemaining, pairs: Object.keys(incoming).length, departures: Object.values(incoming).reduce((n, pair) => n + pair.departures.length, 0) };
  writeFileSync(`${staging}report.json`, `${JSON.stringify(report, null, 2)}\n`);
  console.log(JSON.stringify(report, null, 2));
}
